# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='conditions',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='OK'),
        ),
    ]
