# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rateauthor_ratebook_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='approved_comment',
            new_name='approved_review',
        ),
        migrations.AddField(
            model_name='ratebook',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
