# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20160614_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratebook',
            old_name='vote',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='ratebook',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='ratebook',
            name='rate',
        ),
        migrations.AddField(
            model_name='ratebook',
            name='rate_text',
            field=models.CharField(default='Love it!', max_length=200),
        ),
    ]
